package com.mo.economy_system.common.territory;

public enum TerritoryTeleportResult {
  SUCCESS, TERRITORY_NOT_FOUND, NO_PERMISSION, NO_BACKPOINT, DIMENSION_NOT_FOUND,
  UNSAFE_DESTINATION, NO_RECALL_POTION, COOLDOWN, TELEPORT_FAILED, TELEPORT_STATE_UNKNOWN, ROLLBACK_FAILED
}
