package com.mo.economy_system.common.territory;

import java.util.*;

public final class TerritoryInviteRequestService {
  private static final int MAX_ID_ATTEMPTS=8;
  public record Territory(UUID id,UUID ownerId,String name,Set<UUID> members){public Territory{Objects.requireNonNull(id);Objects.requireNonNull(ownerId);name=validName(name,128,"name");Objects.requireNonNull(members);if(members.stream().anyMatch(Objects::isNull)||members.contains(ownerId))throw new IllegalArgumentException("members");members=Set.copyOf(members);}}
  public record Player(UUID id,String name){public Player{Objects.requireNonNull(id);name=validName(name,64,"name");}}
  public interface Repository{Optional<Territory> find(UUID id) throws Exception;}
  public interface Directory{Optional<Player> online(UUID id) throws Exception;}
  public interface Ids{UUID next();}
  public interface Diagnostics{void warning(String stage,UUID inviter,UUID territory,UUID target,Throwable error);}
  public record Outcome(TerritoryInviteResult result,TerritoryInvite invite){public Outcome{Objects.requireNonNull(result);}}
  private final Repository repository;private final Directory directory;private final TerritoryInviteStore store;private final TerritoryInviteRateLimiter limiter;private final Ids ids;private final Diagnostics diagnostics;private final long lifetime;
  public TerritoryInviteRequestService(Repository r,Directory d,TerritoryInviteStore s,TerritoryInviteRateLimiter l,Ids ids){this(r,d,s,l,ids,(a,b,c,e,f)->{},1200);}
  public TerritoryInviteRequestService(Repository r,Directory d,TerritoryInviteStore s,TerritoryInviteRateLimiter l,Ids ids,Diagnostics diagnostics,long lifetime){repository=Objects.requireNonNull(r);directory=Objects.requireNonNull(d);store=Objects.requireNonNull(s);limiter=Objects.requireNonNull(l);this.ids=Objects.requireNonNull(ids);this.diagnostics=Objects.requireNonNull(diagnostics);if(lifetime<=0)throw new IllegalArgumentException("lifetime");this.lifetime=lifetime;}
  public Outcome create(UUID senderId,String senderName,UUID territoryId,UUID targetId,long tick){Objects.requireNonNull(senderId);Objects.requireNonNull(territoryId);Objects.requireNonNull(targetId);if(tick<0)throw new IllegalArgumentException("tick");senderName=validName(senderName,64,"senderName");
    Territory territory;try{Optional<Territory> found=Objects.requireNonNull(repository.find(territoryId));territory=found.orElse(null);}catch(Exception e){warn("repository",senderId,territoryId,targetId,e);return out(TerritoryInviteResult.CREATE_FAILED);}if(territory==null)return out(TerritoryInviteResult.TERRITORY_NOT_FOUND);if(!territoryId.equals(territory.id())){warn("repository",senderId,territoryId,targetId,new IllegalStateException("territory id mismatch"));return out(TerritoryInviteResult.CREATE_FAILED);}if(!territory.ownerId().equals(senderId))return out(TerritoryInviteResult.NO_PERMISSION);if(targetId.equals(senderId))return out(TerritoryInviteResult.CANNOT_INVITE_SELF);if(targetId.equals(territory.ownerId()))return out(TerritoryInviteResult.CANNOT_INVITE_OWNER);if(territory.members().contains(targetId))return out(TerritoryInviteResult.ALREADY_MEMBER);
    Player target;try{Optional<Player> found=Objects.requireNonNull(directory.online(targetId));target=found.orElse(null);}catch(Exception e){warn("directory",senderId,territoryId,targetId,e);return out(TerritoryInviteResult.CREATE_FAILED);}if(target==null)return out(TerritoryInviteResult.TARGET_OFFLINE);if(!targetId.equals(target.id())){warn("directory",senderId,territoryId,targetId,new IllegalStateException("player id mismatch"));return out(TerritoryInviteResult.CREATE_FAILED);}if(!limiter.allowed(senderId,tick))return out(TerritoryInviteResult.RATE_LIMITED);
    for(int attempt=0;attempt<MAX_ID_ATTEMPTS;attempt++){UUID id;try{id=Objects.requireNonNull(ids.next(),"inviteId");}catch(Exception e){warn("invite-id",senderId,territoryId,targetId,e);return out(TerritoryInviteResult.CREATE_FAILED);}TerritoryInvite invite;try{invite=new TerritoryInvite(id,territory.id(),territory.ownerId(),senderId,targetId,territory.name(),senderName,target.name(),tick,Math.addExact(tick,lifetime));}catch(Exception e){warn("model",senderId,territoryId,targetId,e);return out(TerritoryInviteResult.CREATE_FAILED);}TerritoryInviteStore.PutResult put;try{put=Objects.requireNonNull(store.put(invite,tick));}catch(Exception e){warn("store",senderId,territoryId,targetId,e);return out(TerritoryInviteResult.CREATE_FAILED);}if(put==TerritoryInviteStore.PutResult.ID_COLLISION)continue;if(put==TerritoryInviteStore.PutResult.ALREADY_PENDING){limiter.record(senderId,tick);return out(TerritoryInviteResult.ALREADY_PENDING);}if(put==TerritoryInviteStore.PutResult.FULL)return out(TerritoryInviteResult.STORE_FULL);limiter.record(senderId,tick);return new Outcome(TerritoryInviteResult.SUCCESS,invite);}warn("invite-id",senderId,territoryId,targetId,new IllegalStateException("invite id collision limit"));return out(TerritoryInviteResult.CREATE_FAILED);}
  private void warn(String stage,UUID a,UUID b,UUID c,Throwable e){try{diagnostics.warning(stage,a,b,c,e);}catch(RuntimeException ignored){}}
  private static Outcome out(TerritoryInviteResult r){return new Outcome(r,null);}private static String validName(String value,int max,String field){Objects.requireNonNull(value,field);String v=value.trim();if(v.isEmpty()||v.length()>max)throw new IllegalArgumentException(field);return v;}
}
