package com.mo.economy_system.common.territory;
import java.util.*;
public final class TerritoryInviteDecisionService {
 public enum Result{ACCEPTED,DECLINED,NOT_FOUND,NOT_TARGET,TERRITORY_NOT_FOUND,OWNER_CHANGED,ALREADY_MEMBER,PERSIST_FAILED,STATE_UNKNOWN,BUSY,MULTIPLE_PENDING}
 public enum WriteResult{ADDED,TERRITORY_NOT_FOUND,OWNER_CHANGED,ALREADY_MEMBER,PERSIST_FAILED,STATE_UNKNOWN}
 public interface Repository{WriteResult authorize(UUID territoryId,UUID expectedOwner,UUID playerId,String playerName);}
 public interface Diagnostics{void warning(String stage,TerritoryInvite invite,Throwable error);}
 public record DecisionOutcome(Result result,TerritoryInvite invite){public DecisionOutcome{Objects.requireNonNull(result);}}
 private final TerritoryInviteStore store;private final Repository repository;private final Diagnostics diagnostics;
 public TerritoryInviteDecisionService(TerritoryInviteStore s,Repository r){this(s,r,(a,b,c)->{});}public TerritoryInviteDecisionService(TerritoryInviteStore s,Repository r,Diagnostics d){store=Objects.requireNonNull(s);repository=Objects.requireNonNull(r);diagnostics=Objects.requireNonNull(d);}
 public DecisionOutcome accept(UUID id,UUID actor,String actorName,long tick){TerritoryInviteStore.ClaimResult claimed=store.claim(id,actor,tick);if(claimed.status()!=TerritoryInviteStore.ClaimStatus.CLAIMED)return out(map(claimed.status()),null);TerritoryInviteStore.Claim claim=claimed.claim();TerritoryInvite invite=claim.invite();WriteResult write;try{write=repository.authorize(invite.territoryId(),invite.territoryOwnerId(),actor,actorName);}catch(RuntimeException error){warn("repository",invite,error);return terminal(claim,Result.STATE_UNKNOWN);}if(write==null){warn("repository",invite,new IllegalStateException("null write result"));return terminal(claim,Result.STATE_UNKNOWN);}return switch(write){case ADDED->terminal(claim,Result.ACCEPTED);case TERRITORY_NOT_FOUND->terminal(claim,Result.TERRITORY_NOT_FOUND);case OWNER_CHANGED->terminal(claim,Result.OWNER_CHANGED);case ALREADY_MEMBER->terminal(claim,Result.ALREADY_MEMBER);case STATE_UNKNOWN->terminal(claim,Result.STATE_UNKNOWN);case PERSIST_FAILED->retry(claim);};}
 public DecisionOutcome decline(UUID id,UUID actor,long tick){TerritoryInviteStore.ClaimResult claimed=store.claim(id,actor,tick);if(claimed.status()!=TerritoryInviteStore.ClaimStatus.CLAIMED)return out(map(claimed.status()),null);return terminal(claimed.claim(),Result.DECLINED);}
 public TerritoryInviteStore.SoleResult resolveSole(UUID actor,long tick){return store.resolveSole(actor,tick);}
 private DecisionOutcome retry(TerritoryInviteStore.Claim claim){TerritoryInviteStore.ReleaseResult result=store.release(claim);if(result==TerritoryInviteStore.ReleaseResult.INVALID_CLAIM){warn("release",claim.invite(),new IllegalStateException("invalid claim"));return out(Result.STATE_UNKNOWN,claim.invite());}return out(Result.PERSIST_FAILED,claim.invite());}
 private DecisionOutcome terminal(TerritoryInviteStore.Claim claim,Result success){if(store.complete(claim)!=TerritoryInviteStore.CompleteResult.COMPLETED){warn("complete",claim.invite(),new IllegalStateException("invalid claim"));return out(Result.STATE_UNKNOWN,claim.invite());}return out(success,claim.invite());}
 private void warn(String stage,TerritoryInvite invite,Throwable error){try{diagnostics.warning(stage,invite,error);}catch(RuntimeException ignored){}}
 private static DecisionOutcome out(Result r,TerritoryInvite i){return new DecisionOutcome(r,i);}private static Result map(TerritoryInviteStore.ClaimStatus c){return switch(c){case NOT_FOUND->Result.NOT_FOUND;case NOT_TARGET->Result.NOT_TARGET;case BUSY->Result.BUSY;case CLAIMED->throw new AssertionError();};}
}
