package com.mo.economy_system.common.territory;

public enum TerritoryManagementResult {
  SUCCESS,
  NOT_FOUND,
  NOT_OWNER,
  WRONG_DIMENSION,
  INVALID_TARGET,
  SELF_TARGET,
  NO_CHANGE,
  INVALID_BUFF,
  ALREADY_UNLOCKED,
  NOT_UNLOCKED,
  MAX_LEVEL,
  INVALID_COST,
  INSUFFICIENT_BALANCE,
  INSUFFICIENT_EXPERIENCE,
  INSUFFICIENT_ITEMS,
  INVENTORY_FAILED,
  BALANCE_FAILED,
  PERSIST_FAILED,
  ROLLBACK_FAILED,
  STATE_UNKNOWN
}
