package com.mo.economy_system.common.territory;
public enum TerritoryInviteResult { SUCCESS, TERRITORY_NOT_FOUND, NO_PERMISSION, TARGET_OFFLINE, CANNOT_INVITE_OWNER, CANNOT_INVITE_SELF, ALREADY_MEMBER, ALREADY_PENDING, RATE_LIMITED, STORE_FULL, CREATE_FAILED }
