package com.mo.economy_system.common.transfer;

import com.mo.economy_system.common.check.ClientFileCheckType;
import com.mo.economy_system.common.network.EconomyNetworkLimits;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;

/** Server-scoped, ordered streaming state. It never retains chunks or file contents. */
public final class CheckedFileTransferStore {
  public enum State{AWAITING_TARGET_CONSENT,AWAITING_METADATA,STREAMING,AWAITING_VERIFICATION,COMPLETE}
  public enum Result{CREATED,NOT_FOUND,BUSY,FULL,RATE_LIMITED,WRONG_TARGET,INVALID_METADATA,INVALID_CHUNK,CHUNK_OUT_OF_ORDER,HASH_MISMATCH,SIZE_MISMATCH,REQUESTER_OFFLINE,TARGET_OFFLINE,READY,FORWARD,COMPLETE}
  public record Key(UUID targetPlayerId,UUID requesterPlayerId,ClientFileCheckType checkType,String fileName){public Key{Objects.requireNonNull(targetPlayerId);Objects.requireNonNull(requesterPlayerId);Objects.requireNonNull(checkType);fileName=CheckedFileTransferValidation.fileName(fileName);}}
  public record Pending(Key key,String targetName,String requesterName,long size,String sha256,long createdTick,long expiresTick){public Pending{Objects.requireNonNull(key);sha256=CheckedFileTransferValidation.sha256(sha256);if(size<0||size>EconomyNetworkLimits.MAX_TRANSFER_FILE_BYTES||createdTick<0||expiresTick<=createdTick)throw new IllegalArgumentException("pending");}}
  public record ChunkResult(Result result,boolean consumed,long byteLength,String sha256){}
  private static final class Active{final Pending pending;State state=State.AWAITING_TARGET_CONSENT;UUID transferId;int total;int next;long received;MessageDigest digest;Active(Pending p){pending=p;}}
  private final int capacity;private final LinkedHashMap<Key,Active> active=new LinkedHashMap<>();private final LinkedHashMap<UUID,Long> requesterCooldown=new LinkedHashMap<>();private long lastTick=-1;
  public CheckedFileTransferStore(){this(EconomyNetworkLimits.MAX_PENDING_FILE_TRANSFERS);}public CheckedFileTransferStore(int capacity){if(capacity<1)throw new IllegalArgumentException("capacity");this.capacity=capacity;}
  public synchronized Result create(Pending p,long tick){cleanup(tick);if(active.containsKey(p.key()))return Result.BUSY;Long previous=requesterCooldown.get(p.key().requesterPlayerId());if(previous!=null&&tick-previous<EconomyNetworkLimits.FILE_TRANSFER_COOLDOWN_TICKS)return Result.RATE_LIMITED;if(active.size()>=capacity)return Result.FULL;active.put(p.key(),new Active(p));requesterCooldown.put(p.key().requesterPlayerId(),tick);trim();return Result.CREATED;}
  public synchronized boolean rollback(Pending p,long tick){cleanup(tick);Active a=active.get(p.key());if(a==null||a.pending!=p)return false;active.remove(p.key());requesterCooldown.computeIfPresent(p.key().requesterPlayerId(),(k,v)->v==p.createdTick()?null:v);return true;}
  public synchronized Result ready(Key key,UUID authenticatedTarget,CheckedFileTransferControl meta,long tick){cleanup(tick);Active a=active.get(key);if(a==null)return Result.NOT_FOUND;if(!key.targetPlayerId().equals(authenticatedTarget))return Result.WRONG_TARGET;if(meta.status()!=CheckedFileTransferControlStatus.READY||meta.byteLength()!=a.pending.size()||!meta.sha256().equals(a.pending.sha256())||meta.totalChunks()!=CheckedFileTransferValidation.totalChunks(a.pending.size(),EconomyNetworkLimits.TRANSFER_RAW_CHUNK_BYTES))return fail(key,Result.INVALID_METADATA);a.transferId=meta.transferId();a.total=meta.totalChunks();a.digest=digest();a.state=a.total==0?State.AWAITING_VERIFICATION:State.STREAMING;return a.total==0?finish(a,key):Result.READY;}
  public synchronized ChunkResult chunk(Key key,UUID authenticatedTarget,UUID transferId,int index,int total,byte[] raw,long tick){cleanup(tick);Active a=active.get(key);if(a==null)return new ChunkResult(Result.NOT_FOUND,true,0,null);if(!key.targetPlayerId().equals(authenticatedTarget))return new ChunkResult(Result.WRONG_TARGET,false,0,null);if(a.state!=State.STREAMING||!Objects.equals(a.transferId,transferId)||total!=a.total)return new ChunkResult(fail(key,Result.INVALID_CHUNK),true,0,null);if(index!=a.next)return new ChunkResult(fail(key,Result.CHUNK_OUT_OF_ORDER),true,0,null);long remaining=a.pending.size()-a.received;int expected=(int)Math.min(EconomyNetworkLimits.TRANSFER_RAW_CHUNK_BYTES,remaining);if(raw==null||raw.length!=expected)return new ChunkResult(fail(key,Result.INVALID_CHUNK),true,0,null);a.digest.update(raw);a.received+=raw.length;a.next++;if(a.next==a.total){a.state=State.AWAITING_VERIFICATION;Result done=finish(a,key);return new ChunkResult(done,true,a.pending.size(),a.pending.sha256());}return new ChunkResult(Result.FORWARD,false,0,null);}
  public synchronized boolean discard(Key key,long tick){cleanup(tick);return active.remove(key)!=null;}public synchronized int size(long tick){cleanup(tick);return active.size();}
  public synchronized boolean metadataMatches(Key key,String targetName,String requesterName,long tick){cleanup(tick);Active a=active.get(key);return a!=null&&a.pending.targetName().equals(targetName)&&a.pending.requesterName().equals(requesterName);}
  private Result finish(Active a,Key key){if(a.received!=a.pending.size())return fail(key,Result.SIZE_MISMATCH);String hash=HexFormat.of().formatHex(a.digest.digest());if(!hash.equals(a.pending.sha256()))return fail(key,Result.HASH_MISMATCH);a.state=State.COMPLETE;active.remove(key);return Result.COMPLETE;}
  private Result fail(Key key,Result r){active.remove(key);return r;}private static MessageDigest digest(){try{return MessageDigest.getInstance("SHA-256");}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
  private void cleanup(long tick){if(tick<0)throw new IllegalArgumentException("tick");if(lastTick>=0&&tick<lastTick){active.clear();requesterCooldown.clear();}lastTick=tick;active.entrySet().removeIf(e->tick>=e.getValue().pending.expiresTick());}
  private void trim(){while(requesterCooldown.size()>capacity)requesterCooldown.remove(requesterCooldown.keySet().iterator().next());}
}
