package com.mo.economy_system.common.territory;
import static org.junit.jupiter.api.Assertions.*;import java.util.*;import java.util.concurrent.atomic.*;import org.junit.jupiter.api.Test;
class TerritoryRemovalServiceTest{
 private static final UUID PLAYER=UUID.randomUUID(),LAND=UUID.randomUUID();
 private static TerritoryRemovalService.RemovedTerritory removed(){return new TerritoryRemovalService.RemovedTerritory(LAND,PLAYER,"Home");}
 private static TerritoryRemovalService service(TerritoryRemovalService.Repository repository,TerritoryRemovalRateLimiter limiter,AtomicInteger cleanup,AtomicReference<String> stage){return new TerritoryRemovalService(repository,limiter,(id,t)->cleanup.incrementAndGet(),(id,t)->cleanup.incrementAndGet(),(s,p,id,e)->stage.set(s));}
 @Test void successUsesAuthenticatedOwnerAndCleansAfterRemoval(){AtomicReference<UUID> owner=new AtomicReference<>();AtomicInteger cleanup=new AtomicInteger();var s=service((id,o)->{owner.set(o);return new TerritoryRemovalService.RepositoryOutcome(TerritoryRemovalService.RepositoryResult.REMOVED,removed());},new TerritoryRemovalRateLimiter(),cleanup,new AtomicReference<>());var out=s.remove(PLAYER,LAND,0);assertEquals(TerritoryRemovalService.Result.SUCCESS,out.result());assertEquals(PLAYER,owner.get());assertEquals(2,cleanup.get());}
 @Test void mapsRepositoryResultsAndLimitsAttempts(){for(var entry:Map.of(TerritoryRemovalService.RepositoryResult.NOT_FOUND,TerritoryRemovalService.Result.TERRITORY_NOT_FOUND,TerritoryRemovalService.RepositoryResult.OWNER_MISMATCH,TerritoryRemovalService.Result.NO_PERMISSION,TerritoryRemovalService.RepositoryResult.PERSIST_FAILED,TerritoryRemovalService.Result.PERSIST_FAILED,TerritoryRemovalService.RepositoryResult.STATE_UNKNOWN,TerritoryRemovalService.Result.STATE_UNKNOWN).entrySet()){AtomicInteger cleanup=new AtomicInteger();var s=service((id,o)->new TerritoryRemovalService.RepositoryOutcome(entry.getKey(),null),new TerritoryRemovalRateLimiter(),cleanup,new AtomicReference<>());assertEquals(entry.getValue(),s.remove(PLAYER,LAND,0).result());assertEquals(TerritoryRemovalService.Result.RATE_LIMITED,s.remove(PLAYER,UUID.randomUUID(),19).result());assertEquals(0,cleanup.get());}}
 @Test void nullExceptionAndContractViolationsAreUnknown(){AtomicReference<String> stage=new AtomicReference<>();var nullService=service((id,o)->null,new TerritoryRemovalRateLimiter(),new AtomicInteger(),stage);assertEquals(TerritoryRemovalService.Result.STATE_UNKNOWN,nullService.remove(PLAYER,LAND,0).result());assertEquals("repository",stage.get());var mismatch=service((id,o)->new TerritoryRemovalService.RepositoryOutcome(TerritoryRemovalService.RepositoryResult.REMOVED,new TerritoryRemovalService.RemovedTerritory(UUID.randomUUID(),PLAYER,"x")),new TerritoryRemovalRateLimiter(),new AtomicInteger(),stage);assertEquals(TerritoryRemovalService.Result.STATE_UNKNOWN,mismatch.remove(PLAYER,LAND,0).result());assertEquals("repository-contract",stage.get());var thrown=service((id,o)->{throw new IllegalStateException();},new TerritoryRemovalRateLimiter(),new AtomicInteger(),stage);assertEquals(TerritoryRemovalService.Result.STATE_UNKNOWN,thrown.remove(PLAYER,LAND,0).result());assertThrows(AssertionError.class,()->service((id,o)->{throw new AssertionError();},new TerritoryRemovalRateLimiter(),new AtomicInteger(),stage).remove(PLAYER,LAND,0));}
 @Test void cleanupAndDiagnosticsFailuresDoNotChangeSuccess(){var s=new TerritoryRemovalService((id,o)->new TerritoryRemovalService.RepositoryOutcome(TerritoryRemovalService.RepositoryResult.REMOVED,removed()),new TerritoryRemovalRateLimiter(),(id,t)->{throw new IllegalStateException();},(id,t)->{throw new IllegalStateException();},(a,b,c,d)->{throw new IllegalStateException();});assertEquals(TerritoryRemovalService.Result.SUCCESS,s.remove(PLAYER,LAND,0).result());}
 @Test void limiterBoundaryCapacityAndEpochReset(){var l=new TerritoryRemovalRateLimiter(1);assertTrue(l.acquire(PLAYER,0));assertFalse(l.acquire(PLAYER,19));assertTrue(l.acquire(PLAYER,20));assertTrue(l.acquire(UUID.randomUUID(),21));assertTrue(l.acquire(PLAYER,22));assertTrue(l.acquire(PLAYER,1));assertThrows(IllegalArgumentException.class,()->l.acquire(PLAYER,-1));}
}
