package com.mo.economy_system.common.territory;
import static org.junit.jupiter.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;
class TerritoryInviteStoreTest {private static TerritoryInvite invite(UUID id,UUID territory,UUID target,long from,long to){UUID owner=UUID.randomUUID();return new TerritoryInvite(id,territory,owner,owner,target,"land","owner","target",from,to);}
  @org.junit.jupiter.api.Test void rejectsInvalidInsertionTimesWithoutChangingIndexes(){TerritoryInviteStore store=new TerritoryInviteStore();UUID territory=UUID.randomUUID(),target=UUID.randomUUID();org.junit.jupiter.api.Assertions.assertThrows(IllegalArgumentException.class,()->store.put(invite(UUID.randomUUID(),territory,target,11,20),10));org.junit.jupiter.api.Assertions.assertThrows(IllegalArgumentException.class,()->store.put(invite(UUID.randomUUID(),territory,target,0,10),10));org.junit.jupiter.api.Assertions.assertEquals(0,store.size(10));org.junit.jupiter.api.Assertions.assertTrue(store.consistent());}
 @Test void collisionNeverOverwritesOrPoisonsKey(){TerritoryInviteStore s=new TerritoryInviteStore();UUID id=UUID.randomUUID(),target=UUID.randomUUID();TerritoryInvite first=invite(id,UUID.randomUUID(),target,0,10),collision=invite(id,UUID.randomUUID(),UUID.randomUUID(),0,10);assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(first,0));assertEquals(TerritoryInviteStore.PutResult.ID_COLLISION,s.put(collision,0));assertEquals(first,s.find(id,0).orElseThrow());assertTrue(s.consistent());assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(invite(UUID.randomUUID(),collision.territoryId(),collision.targetPlayerId(),0,10),0));}
 @Test void dedupeAndIndependentKeys(){TerritoryInviteStore s=new TerritoryInviteStore();UUID t=UUID.randomUUID(),land=UUID.randomUUID();assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(invite(UUID.randomUUID(),land,t,0,10),0));assertEquals(TerritoryInviteStore.PutResult.ALREADY_PENDING,s.put(invite(UUID.randomUUID(),land,t,0,10),0));assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(invite(UUID.randomUUID(),UUID.randomUUID(),t,0,10),0));assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(invite(UUID.randomUUID(),land,UUID.randomUUID(),0,10),0));assertTrue(s.consistent());}
 @Test void claimTokenProtectsCompleteAndRelease(){TerritoryInviteStore s=new TerritoryInviteStore();TerritoryInvite i=invite(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),0,10);s.put(i,0);var claimed=s.claim(i.inviteId(),i.targetPlayerId(),1);assertEquals(i,claimed.claim().invite());assertEquals(TerritoryInviteStore.ClaimStatus.BUSY,s.claim(i.inviteId(),i.targetPlayerId(),1).status());var forged=new TerritoryInviteStore.Claim(claimed.claim().token()+1,i);assertEquals(TerritoryInviteStore.CompleteResult.INVALID_CLAIM,s.complete(forged));assertEquals(TerritoryInviteStore.ReleaseResult.INVALID_CLAIM,s.release(forged));assertEquals(TerritoryInviteStore.ReleaseResult.RELEASED,s.release(claimed.claim()));assertEquals(TerritoryInviteStore.ClaimStatus.CLAIMED,s.claim(i.inviteId(),i.targetPlayerId(),2).status());}
 @Test void processingSurvivesExpiryThenReleaseExpires(){TerritoryInviteStore s=new TerritoryInviteStore();TerritoryInvite i=invite(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),0,2);s.put(i,0);var claim=s.claim(i.inviteId(),i.targetPlayerId(),1).claim();assertEquals(1,s.size(2));assertEquals(TerritoryInviteStore.ReleaseResult.EXPIRED,s.release(claim));assertEquals(0,s.size(2));assertTrue(s.consistent());}
 @Test void completeRemovesBothIndexesAndEpochResetClears(){TerritoryInviteStore s=new TerritoryInviteStore();TerritoryInvite i=invite(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),5,20);s.put(i,5);var claim=s.claim(i.inviteId(),i.targetPlayerId(),6).claim();assertEquals(TerritoryInviteStore.CompleteResult.COMPLETED,s.complete(claim));assertTrue(s.consistent());assertEquals(TerritoryInviteStore.PutResult.CREATED,s.put(invite(UUID.randomUUID(),i.territoryId(),i.targetPlayerId(),6,20),6));assertEquals(0,s.size(0));assertTrue(s.consistent());}
 @Test void soleIsAtomicAndCapacityBounded(){TerritoryInviteStore s=new TerritoryInviteStore(2);UUID target=UUID.randomUUID();assertEquals(TerritoryInviteStore.SoleStatus.NONE,s.resolveSole(target,0).status());s.put(invite(UUID.randomUUID(),UUID.randomUUID(),target,0,10),0);assertEquals(TerritoryInviteStore.SoleStatus.SOLE,s.resolveSole(target,0).status());s.put(invite(UUID.randomUUID(),UUID.randomUUID(),target,0,10),0);assertEquals(TerritoryInviteStore.SoleStatus.MULTIPLE,s.resolveSole(target,0).status());assertEquals(TerritoryInviteStore.PutResult.FULL,s.put(invite(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),0,10),0));}}
