#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Dec 19 18:45:54 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=(\u6C49\u5316)Kappa_v5.3.zip
