package com.mo.economy_system.common.market;
import static org.junit.jupiter.api.Assertions.*;
import com.mo.economy_system.common.network.RemoveDemandOrderMessage;
import com.mo.economy_system.core.economy_system.BalanceMutationResult;
import java.util.UUID;
import org.junit.jupiter.api.Test;
class CancelDemandOrderServiceTest {
  @Test void ownerAndOperatorRefundOriginalOwnerExactlyOnce(){Fixture owner=new Fixture();assertEquals(CancelDemandOrderResult.SUCCESS,owner.execute().result());assertEquals(117,owner.account.balance);assertEquals(1,owner.account.credits);assertEquals(CancelDemandOrderResult.NOT_FOUND,owner.execute().result());Fixture op=new Fixture();op.actor=UUID.randomUUID();op.operator=true;assertEquals(CancelDemandOrderResult.SUCCESS,op.execute().result());assertEquals(op.owner,op.account.lastOwner);}
  @Test void validationNeverMutates(){Fixture f=new Fixture();f.actor=UUID.randomUUID();assertEquals(CancelDemandOrderResult.NOT_OWNER,f.execute().result());assertNotNull(f.repository.order);f=new Fixture();f.repository.order=f.order(MarketOrderType.DEMAND,true);assertEquals(CancelDemandOrderResult.ALREADY_DELIVERED,f.execute().result());f=new Fixture();f.repository.order=f.order(MarketOrderType.SALES,false);assertEquals(CancelDemandOrderResult.WRONG_ORDER_TYPE,f.execute().result());}
  @Test void removalStatesAreExplicit(){Fixture f=new Fixture();f.repository.status=DemandOrderRemovalStatus.ORDER_CHANGED;assertEquals(MarketMutationState.CHANGED,f.execute().mutationState());f=new Fixture();f.repository.status=DemandOrderRemovalStatus.PERSIST_FAILED;assertEquals(MarketMutationState.UNCHANGED,f.execute().mutationState());}
  @Test void refundFailureRestoresOrder(){Fixture f=new Fixture();f.account.creditResult=BalanceMutationResult.PERSIST_FAILED;CancelDemandOrderOutcome o=f.execute();assertEquals(CancelDemandOrderResult.REFUND_FAILED,o.result());assertEquals(MarketMutationState.UNCHANGED,o.mutationState());assertNotNull(f.repository.order);}
  @Test void rollbackFailureMarksMarketChangedForInvalidation(){Fixture f=new Fixture();f.account.creditResult=BalanceMutationResult.PERSIST_FAILED;f.repository.restoreResult=MarketOrderRestoreResult.PERSIST_FAILED;CancelDemandOrderOutcome o=f.execute();assertEquals(CancelDemandOrderResult.ROLLBACK_FAILED,o.result());assertEquals(MarketMutationState.CHANGED,o.mutationState());var plan=MarketActionPostPlan.build(o.mutationState(),true,false,()->{},()->{},()->{});assertEquals("broadcast",plan.get(0).stage());}
  private static final class Fixture {UUID owner=UUID.randomUUID(),actor=owner;boolean operator;Account account=new Account();Repository repository=new Repository();Fixture(){repository.order=order(MarketOrderType.DEMAND,false);}MarketOrder order(MarketOrderType t,boolean d){return new MarketOrder(t,UUID.randomUUID(),MarketOrderCodecTest.item(),2,17,"buyer",owner,1,2,d);}CancelDemandOrderOutcome execute(){UUID id=repository.order==null?UUID.randomUUID():repository.order.tradeId();return CancelDemandOrderService.execute(new RemoveDemandOrderMessage(id),new CancelDemandOrderService.Context(actor,operator,account,repository,CancelDemandOrderService.FailureReporter.noop()));}}
  private static final class Account implements CancelDemandOrderService.Account {int balance=100,credits;UUID lastOwner;BalanceMutationResult previewResult=BalanceMutationResult.SUCCESS,creditResult=BalanceMutationResult.SUCCESS;public BalanceMutationResult previewCreditExact(UUID owner,int amount){return previewResult;}public BalanceMutationResult creditExact(UUID owner,int amount){credits++;lastOwner=owner;if(creditResult==BalanceMutationResult.SUCCESS)balance+=amount;return creditResult;}}
  private static final class Repository implements CancelDemandOrderService.Repository {MarketOrder order;DemandOrderRemovalStatus status=DemandOrderRemovalStatus.REMOVED;MarketOrderRestoreResult restoreResult=MarketOrderRestoreResult.RESTORED;public MarketOrder find(UUID id){return order;}public DemandOrderRemovalResult removeUndeliveredDemandIfUnchanged(UUID id,MarketOrder expected){if(status!=DemandOrderRemovalStatus.REMOVED)return DemandOrderRemovalResult.failure(status);MarketOrder removed=order;order=null;return DemandOrderRemovalResult.removed(new MarketOrderRemoval(removed,()->{if(restoreResult==MarketOrderRestoreResult.RESTORED)order=removed;return restoreResult;}));}}
}
