package com.mo.economy_system.common.market;
import com.mo.economy_system.common.network.ConfirmDemandOrderMessage;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class ConfirmDemandOrderServiceTest{
 @Test void ownerConfirmsOnceAndReceivesAll(){Fixture f=new Fixture();assertEquals(ConfirmDemandOrderResult.SUCCESS,f.run().result());assertEquals(3,f.inventory.count);assertNull(f.repository.current);assertEquals(ConfirmDemandOrderResult.NOT_FOUND,f.run().result());assertEquals(3,f.inventory.count);}
 @Test void operatorUsesOnlineOwnerInventory(){Fixture f=new Fixture();f.actor=UUID.randomUUID();f.operator=true;assertEquals(ConfirmDemandOrderResult.SUCCESS,f.run().result());assertEquals(3,f.inventory.count);assertNotEquals(f.actor,f.inventory.ownerId());}
 @Test void permissionTypeDeliveryAndOwnerOnlineAreValidated(){Fixture f=new Fixture();f.actor=UUID.randomUUID();assertEquals(ConfirmDemandOrderResult.NOT_OWNER,f.run().result());f=new Fixture();f.repository.current=f.order(MarketOrderType.SALES,false);assertEquals(ConfirmDemandOrderResult.WRONG_ORDER_TYPE,f.run().result());f=new Fixture();f.repository.current=f.order(MarketOrderType.DEMAND,false);assertEquals(ConfirmDemandOrderResult.NOT_DELIVERED,f.run().result());f=new Fixture();f.online=false;assertEquals(ConfirmDemandOrderResult.OWNER_OFFLINE,f.run().result());}
 @Test void capacityAndMaterializationFailuresDoNotDelete(){Fixture f=new Fixture();f.inventory.accept=false;assertEquals(ConfirmDemandOrderResult.INVENTORY_FULL,f.run().result());assertNotNull(f.repository.current);f=new Fixture();f.restoreFails=true;assertEquals(ConfirmDemandOrderResult.ITEM_RESTORE_FAILED,f.run().result());assertNotNull(f.repository.current);}
 @Test void changedOrderAndInsertionFailureRestoreOrder(){Fixture f=new Fixture();f.repository.removedOverride=new MarketOrder(MarketOrderType.DEMAND,f.trade,MarketOrderCodecTest.item(),3,10,"changed",f.owner,2,3,true);assertEquals(ConfirmDemandOrderResult.ORDER_CHANGED,f.run().result());assertNotNull(f.repository.current);f=new Fixture();f.inventory.insertSuccess=false;ConfirmDemandOrderOutcome o=f.run();assertEquals(ConfirmDemandOrderResult.INVENTORY_MUTATION_FAILED,o.result());assertFalse(o.marketChanged());assertNotNull(f.repository.current);}
 @Test void nullRepositoryAndInsertionFailClosed(){Fixture f=new Fixture();f.repository.returnNull=true;assertTrue(f.run().marketChanged());f=new Fixture();f.inventory.returnNull=true;ConfirmDemandOrderOutcome o=f.run();assertEquals(ConfirmDemandOrderResult.ROLLBACK_FAILED,o.result());assertFalse(o.marketChanged());}
 @Test void reporterExceptionCannotChangeRollbackResult(){Fixture f=new Fixture();f.inventory.insertSuccess=false;f.reporterThrows=true;assertEquals(ConfirmDemandOrderResult.INVENTORY_MUTATION_FAILED,f.run().result());}
 private static final class Fixture{UUID owner=UUID.randomUUID(),actor=owner,trade=UUID.randomUUID();boolean operator,online=true,restoreFails,reporterThrows;FakeInventory inventory=new FakeInventory();FakeRepository repository=new FakeRepository();Fixture(){repository.current=order(MarketOrderType.DEMAND,true);}MarketOrder order(MarketOrderType type,boolean delivered){return new MarketOrder(type,trade,MarketOrderCodecTest.item(),3,10,"owner",owner,1,2,delivered);}ConfirmDemandOrderOutcome run(){return ConfirmDemandOrderService.execute(new ConfirmDemandOrderMessage(trade),new ConfirmDemandOrderService.Context(actor,operator,o->{if(restoreFails)throw new IllegalStateException();return new Object();},id->online?Optional.of(inventory):Optional.empty(),repository,(a,b,c,d,e,f,g,h,i)->{if(reporterThrows)throw new IllegalStateException();}));}final class FakeInventory implements TransactionalInventory{int count;boolean accept=true,insertSuccess=true,returnNull;public UUID ownerId(){return owner;}public boolean canAccept(Object o,int q){return accept;}public InventoryInsertionResult insert(Object o,int q){if(returnNull)return null;if(!insertSuccess)return InventoryInsertionResult.failure(true);count+=q;return InventoryInsertionResult.success(()->{count-=q;return true;});}}final class FakeRepository implements ConfirmDemandOrderService.Repository{MarketOrder current,removedOverride;boolean returnNull,restore=true;public MarketOrder find(UUID id){return current;}public DeliveredDemandRemovalResult removeDeliveredDemandTransactional(UUID id){if(returnNull)return null;MarketOrder removed=removedOverride==null?current:removedOverride;current=null;return DeliveredDemandRemovalResult.removed(new MarketOrderRemoval(removed,()->{if(!restore)return MarketOrderRestoreResult.PERSIST_FAILED;current=removed;return MarketOrderRestoreResult.RESTORED;}));}}}
}
