package com.mo.economy_system.common.client;
import com.mo.economy_system.common.network.*;import org.junit.jupiter.api.*;import java.util.List;import static org.junit.jupiter.api.Assertions.*;
class ClientMarketStateTest{
 @BeforeEach void reset(){ClientMarketState.reset();}
 @Test void onlyLatestRequestedPageAndRevisionApply(){long old=ClientMarketState.nextPageRequestId(),latest=ClientMarketState.nextPageRequestId();assertFalse(ClientMarketState.apply(page(old,1)));assertFalse(ClientMarketState.apply(page(latest+1,1)));assertTrue(ClientMarketState.apply(page(latest,2)));assertEquals(2,ClientMarketState.snapshot().marketRevision());}
 @Test void summaryAndInvalidationHaveIndependentOrdering(){long summary=ClientMarketState.nextSummaryRequestId();assertTrue(ClientMarketState.apply(summary(summary,2)));ClientMarketState.apply(MarketDataResponseMessage.invalidated(3,4,5));assertFalse(ClientMarketState.apply(summary(summary,2)));assertEquals(4,ClientMarketState.snapshot().totalSales());assertTrue(ClientMarketState.snapshot().stale());}
 @Test void invalidationPreservesPageAndResetDoesNotReuseIds(){long page=ClientMarketState.nextPageRequestId();ClientMarketState.apply(page(page,1));var orders=ClientMarketState.snapshot().orders();long before=page;ClientMarketState.apply(MarketDataResponseMessage.invalidated(2,1,1));assertEquals(orders,ClientMarketState.snapshot().orders());ClientMarketState.reset();assertTrue(ClientMarketState.nextPageRequestId()>before);}
 @Test void pageErrorPreservesData(){long page=ClientMarketState.nextPageRequestId();ClientMarketState.apply(page(page,1));assertTrue(ClientMarketState.pageError(page,1,"sync"));assertEquals("sync",ClientMarketState.snapshot().error());assertFalse(ClientMarketState.snapshot().loading());}
 @Test void stalePageErrorCannotClearNewLoading(){long old=ClientMarketState.nextPageRequestId();long latest=ClientMarketState.nextPageRequestId();assertFalse(ClientMarketState.pageError(old,0,"stale"));assertEquals(latest,ClientMarketState.snapshot().latestPageRequestId());assertTrue(ClientMarketState.snapshot().loading());}
 private static MarketDataResponseMessage page(long id,long revision){return new MarketDataResponseMessage(MarketDataResponseKind.PAGE,id,revision,0,9,0,0,0,List.of());}
 private static MarketDataResponseMessage summary(long id,long revision){return new MarketDataResponseMessage(MarketDataResponseKind.SUMMARY,id,revision,0,0,0,0,0,List.of());}
}
