package com.mo.economy_system.common.market;

public enum CancelDemandOrderResult {
    SUCCESS, INVALID_CONTEXT, NOT_FOUND, WRONG_ORDER_TYPE, ALREADY_DELIVERED,
    NOT_OWNER, INVALID_PRICE, OWNER_BALANCE_LIMIT, ORDER_REMOVE_FAILED,
    REFUND_FAILED, ORDER_CHANGED, ROLLBACK_FAILED, STATE_UNKNOWN
}
