package com.mo.economy_system.common.market;

public enum CreateDemandOrderResult {
    SUCCESS, INVALID_CONTEXT, INVALID_ITEM_ID, ITEM_NOT_FOUND, INVALID_QUANTITY,
    QUANTITY_EXCEEDS_LIMIT, INVALID_PRICE, SNAPSHOT_REJECTED, INSUFFICIENT_FUNDS,
    REPOSITORY_FULL, ID_GENERATION_FAILED, TIME_OVERFLOW, PAYMENT_FAILED,
    ORDER_PERSIST_FAILED, REFUND_FAILED
}
