package com.mo.economy_system.common.market;

public enum CreateSalesOrderResult {
    SUCCESS, INVALID_CONTEXT, INVALID_SLOT, INVALID_QUANTITY, INVALID_PRICE, EMPTY_SLOT,
    INSUFFICIENT_ITEMS, SNAPSHOT_REJECTED, TAX_OVERFLOW, INSUFFICIENT_FUNDS,
    REPOSITORY_FULL, INVENTORY_MUTATION_FAILED, TAX_MUTATION_FAILED, ORDER_PERSIST_FAILED,
    ROLLBACK_FAILED, STATE_UNKNOWN
}
