package com.mo.economy_system.common.market;

public enum DemandOrderDeliveryResult {
  SUCCESS,
  INVALID_CONTEXT,
  NOT_FOUND,
  WRONG_ORDER_TYPE,
  ALREADY_DELIVERED,
  SELF_DELIVERY,
  INVALID_PRICE,
  INVALID_QUANTITY,
  INVALID_SNAPSHOT,
  ITEM_RESTORE_FAILED,
  INVENTORY_CONTEXT_FAILED,
  INSUFFICIENT_ITEMS,
  RECIPIENT_BALANCE_LIMIT,
  INVENTORY_MUTATION_FAILED,
  PAYMENT_FAILED,
  ORDER_CHANGED,
  LEDGER_UPDATE_FAILED,
  LEDGER_STATE_UNKNOWN,
  ROLLBACK_FAILED
}
