package com.mo.economy_system.common.market;

public enum PurchaseSalesOrderResult {
    SUCCESS, INVALID_CONTEXT, NOT_FOUND, WRONG_ORDER_TYPE, SELF_PURCHASE, INVALID_PRICE,
    INVALID_QUANTITY, INVALID_SNAPSHOT, ITEM_RESTORE_FAILED, INSUFFICIENT_FUNDS,
    SELLER_BALANCE_LIMIT, INVENTORY_FULL, PARTIAL_FILL_UNSUPPORTED, ORDER_CHANGED, ORDER_REMOVE_FAILED,
    INVENTORY_MUTATION_FAILED, PAYMENT_FAILED, ROLLBACK_FAILED
}
