package com.mo.economy_system.common.market;

public enum RemoveSalesOrderResult {
    SUCCESS, INVALID_CONTEXT, NOT_FOUND, WRONG_ORDER_TYPE, NOT_OWNER, OWNER_OFFLINE,
    INVALID_PRICE, INVALID_QUANTITY, INVALID_SNAPSHOT, ITEM_RESTORE_FAILED, INVENTORY_FULL,
    ORDER_CHANGED, ORDER_REMOVE_FAILED, INVENTORY_MUTATION_FAILED, ROLLBACK_FAILED
}
